### ISSUE TITLE
Keep the string as it is (not converting unicode)

### ISSUE THREAD

**Issue by kexincui** [Tblue/python-jproperties#11]
sample input properties file:  `key=\u6c9cb\u82310`

And I want the output to be exact like: `\u6c9cb\u82310`.

This is what I did: `Properties(process_escapes_in_values=False).load(f, "utf-8")`

And this is what I get:` \\u6c9cb\\u82310`

Is there a way to get the exact string not with the extra \\?  Thanks!

**Comment by Tblue** [comment]
Sorry for the very late reply!

You have set `process_escapes_in_values=False`, and the option is doing what it is supposed to: Escape sequences in values are not processed when reading the file, so the backslashes in your input file are treated literally. If you `print` the value of the property `key`, you will see that the string that the library parsed is literally `\u6c9cb\u82310`. 

On output, however, the backslashes are then escaped, giving you `\\u6c9cb\\u82310` since the library tries very hard to produce valid Java property files that can be read by _other_ standards-conforming property file parsers: If a standards-conforming parser parses `\\u6c9cb\\u82310`, it will decode that to `\u6c9cb\u82310`, which is what _we_ read in originally.

Try setting `process_escapes_in_values=True` instead (or don't specify the option at all). That should give you the expected result.

---

To elaborate: `process_escapes_in_values=False` is a horrible kludge to allow parsing property-_like_ property files that are not actually Java property files, but look like they are. Some _very_ simplistic property file parsers don't support escape sequences at all, so files that are read by those parsers don't escape backslashes properly. To allow _us_ to read those property files correctly, there exists `process_escapes_in_values=False`.
