### ISSUE TITLE
What is the usefulness of metadata?

### ISSUE THREAD

**Issue by michaelwiles** [Tblue/python-jproperties#9]
Firstly, thank you very much this library. I'm a java dev coming into python and I really appreciate that you've implemented the familiar properties api in python.

I guess, not being used the idea of the metadata I'm wondering what use there is for it?

And also can I just confirm _how_ to use it...

Can I confirm that given this properties file:

> #: meta_key_1=meta_value
> key=value

So if I read in that file then the key property would have meta data meta_key_1 associated with it right?

So meta data keys are placed before the key they're coloring. But as far I can tell, _doc meta data keys must be placed after that?

**Comment by Tblue** [comment]
Sorry for the (very) late reply.

The idea behind metadata is that you can attach _additional_ key-value pairs to a key-value pair, and access them programmatically.

For example, imagine your property file contains localization strings. Many localization platforms allow setting a maximum length for localized strings (so that buttons don't contain overflowing text, and so on). You could attach that information to the string like this (as you said, metadata _precedes_ the key-value pair that it belongs to):

```properties
#: max_length = 50
BUTTON.OK = Accept
```

Then, you could access the `max_length` metadata for the `BUTTON.OK` property in your program later on.

`_doc` metadata is just a nice way to attach machine-readable comments to key-value pairs. As you said, it must follow the pair it belongs to. You could do the same using the normal metadata mechanism explained above, but then you would have to put the entire comment into one line.

To continue the above example, many localization platforms also allow attaching developer comments to strings, explaining what the string is used for. For example:

```properties
#: max_length = 50
BUTTON.OK = Accept
# Dialog button that allows user to accept changes.
# Please keep short.
```

This will allow you to access the comment after the key-value pair as `_doc` metadata.

I hope that helps.
